# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ae3f9ab8ef7d541f424beb70ae9da06ae6438343a7a76a4bac76c41a07f9dae331ab07a4f4eb724591bde6e9326bb2c3121dfa77aec74b6ee9bf8e150676833

test:
  secret_key_base: 569a698bdfe7832627333b122883bb2afe8642bf83a59c38ca107859e11397e7d5fdb3f89a5b85d83edb7e63496ec0a589531f5189c634f2d8b826a050d86e39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
